# Use official Python image
FROM python:3.9-slim

WORKDIR /app

# Copy requirements and install
COPY code/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY code/ .

# Expose Flask port
EXPOSE 8000

# Set environment variable for Flask
ENV FLASK_APP=ingest.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=8000

# Run the Flask app
CMD ["flask", "run"]
